---
stages:
  - syntax
  - unit

cache:
  paths:
    - vendor/bundle

before_script:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
  - bundle install --without system_tests --path vendor/bundle --jobs $(nproc)

syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop-Ruby 2.5.3-Puppet ~> 6:
  stage: syntax
  image: ruby:2.5.3
  script:
    - bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
  variables:
    PUPPET_GEM_VERSION: '~> 6'

parallel_spec-Ruby 2.5.3-Puppet ~> 6:
  stage: unit
  image: ruby:2.5.3
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 6'

parallel_spec-Ruby 2.4.5-Puppet ~> 5:
  stage: unit
  image: ruby:2.4.5
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 5'

acceptance-Ruby 2.4.4-Puppet ~> 5.5:
  stage: acceptance
  when: on_success
  except:
    - tags
    - /^master$/
  tags:
    - pdk
  script:
    - rvm use 2.4.4
    - gem install bundle
    - rm -f Gemfile.lock
    - gem update --system
    - bundle install --jobs $(nproc)
    - bundle exec rake beaker:default
  variables:
    PUPPET_GEM_VERSION: '~> 5'
    PDK_PUPPET_VERSION: '5'

acceptance-Ruby 2.4.4-Puppet ~> 6.5:
  stage: acceptance
  when: on_success
  except:
    - tags
    - /^master$/
  tags:
    - pdk
  script:
    - rvm use 2.5.3
    - gem install bundle
    - rm -f Gemfile.lock
    - gem update --system
    - bundle install --jobs $(nproc)
    - bundle exec rake beaker:default
  variables:
    PUPPET_GEM_VERSION: '~> 6'
    PDK_PUPPET_VERSION: '6'

build:
  stage: build
  tags:
    - pdk
  only:
    - tags
  script:
    - rvm use 2.4.4
    - gem install bundle
    - rm -f Gemfile.lock
    - gem update --system
    - bundle install --jobs $(nproc)
    - mkdir builds/
    - bundle exec rake module:bump_to_version[${CI_COMMIT_TAG}]
    - pdk build --target-dir=builds/
  variables:
    PDK_PUPPET_VERSION: '5.5'
    PUPPET_GEM_VERSION: '~> 5.5'
  artifacts:
    paths:
      - builds/phoenixnap-ca_trust*
