---
variables:
  BASH_ENV: /etc/profile

stages:
  - syntax
  - unit
  - acceptance
  - build

pdk validate Puppet ~> 5.5:
  stage: syntax
  tags:
    - pdk
  except:
    - tags
  script:
    - pdk validate
  variables:
    PDK_PUPPET_VERSION: '5.5'

pdk validate Puppet ~> 6.5:
  stage: syntax
  tags:
    - pdk
  except:
    - tags
  script:
    - pdk validate
  variables:
    PDK_PUPPET_VERSION: '6.5'

pdk test unit Puppet ~> 5.5:
  stage: unit
  when: on_success
  except:
    - tags
  tags:
    - pdk
  script:
    - pdk test unit
  variables:
    PDK_PUPPET_VERSION: '5.5'

pdk test unit Puppet ~> 6.5:
  stage: unit
  when: on_success
  except:
    - tags
  tags:
    - pdk
  script:
    - pdk test unit
  variables:
    PDK_PUPPET_VERSION: '6.5'


acceptance-Ruby 2.4.4-Puppet ~> 5.5:
  stage: acceptance
  when: on_success
  except: 
    - tags
    - /^master$/
  tags:
    - pdk
  script:
    - rvm use 2.4.4
    - gem install bundle
    - rm -f Gemfile.lock
    - gem update --system
    - bundle install --jobs $(nproc)
    - bundle exec rake beaker:default
  variables:
    PUPPET_GEM_VERSION: '~> 5.5'
    PDK_PUPPET_VERSION: '5.5'

acceptance-Ruby 2.4.4-Puppet ~> 6.5:
  stage: acceptance
  when: on_success
  except:
    - tags
    - /^master$/
  tags:
    - pdk
  script:
    - rvm use 2.5.3
    - gem install bundle
    - rm -f Gemfile.lock
    - gem update --system
    - bundle install --jobs $(nproc)
    - bundle exec rake beaker:default
  variables:
    PUPPET_GEM_VERSION: '~> 6.5'
    PDK_PUPPET_VERSION: '6.5'


build:
  stage: build
  tags:
    - pdk
  only:
    - tags
  script:
    - rvm use 2.4.4
    - gem install bundle
    - rm -f Gemfile.lock
    - gem update --system
    - bundle install --jobs $(nproc)
    - mkdir builds/
    - bundle exec rake module:bump_to_version[${CI_COMMIT_TAG}]
    - pdk build --target-dir=builds/
  variables:
    PDK_PUPPET_VERSION: '5.5'
    PUPPET_GEM_VERSION: '~> 5.5'
  artifacts:
    paths:
      - builds/phoenixnap-ca_trust*
