---
HOSTS:
  centos7-64-1:
    type: aio
    hypervisor: docker
    docker_cmd:
      - "/sbin/init"
    image: centos:7
    platform: el-7-x86_64
    packaging_platform: el-7-x86_64
    docker_image_commands:
      - ln -sf ../usr/share/zoneinfo/America/Phoenix /etc/localtime
      - systemctl mask getty@tty1.service
      - yum install -y crontabs initscripts iproute openssl sysvinit-tools tar wget which ss
    roles:
      - agent
      - default
  centos8-64-1:
    type: aio
    hypervisor: docker
    docker_cmd:
      - "/sbin/init"
    image: centos:8
    platform: el-8-x86_64
    packaging_platform: el-8-x86_64
    docker_image_commands:
      - ln -sf ../usr/share/zoneinfo/America/Phoenix /etc/localtime
      - systemctl mask getty@tty1.service
      - yum install -y crontabs initscripts openssl wget which
    roles:
      - agent
  debian9-64-1:
    type: aio
    hypervisor: docker
    docker_cmd:
      - "/sbin/init"
    image: debian:9
    platform: debian-9-amd64
    packaging_platform: debian-9-amd64
    docker_image_commands:
      - ln -sf ../usr/share/zoneinfo/America/Phoenix /etc/localtime
      - rm -f /usr/sbin/policy-rc.d
      - systemctl mask getty@tty1.service getty-static.service
      - apt-get update && apt-get install -y cron locales-all net-tools wget systemd-sysv
    roles:
      - agent
  debian10-64-1:
    type: aio
    hypervisor: docker
    docker_cmd:
      - "/sbin/init"
    image: debian:10
    platform: debian-10-amd64
    packaging_platform: debian-10-amd64
    docker_image_commands:
      - ln -sf ../usr/share/zoneinfo/America/Phoenix /etc/localtime
      - rm -f /usr/sbin/policy-rc.d
      - systemctl mask getty@tty1.service getty-static.service
      - apt-get update && apt-get install -y cron locales-all net-tools wget systemd-sysv
    roles:
      - agent
  ubuntu1604-64-1:
    type: aio
    hypervisor: docker
    docker_cmd:
      - "/sbin/init"
    image: ubuntu:16.04
    platform: ubuntu-16.04-amd64
    packaging_platform: ubuntu-16.04-amd64
    docker_image_commands:
      - ln -sf ../usr/share/zoneinfo/America/Phoenix /etc/localtime
      - systemctl mask getty@tty1.service getty-static.service
      - apt-get install -y net-tools wget locales apt-transport-https
      - locale-gen en_US.UTF-8
      - echo LANG=en_US.UTF-8 > /etc/default/locale
    roles:
      - agent
  ubuntu1804-64-1:
    type: aio
    hypervisor: docker
    docker_cmd:
      - "/sbin/init"
    image: ubuntu:18.04
    platform: ubuntu-18.04-amd64
    packaging_platform: ubuntu-18.04-amd64
    docker_image_commands:
      - ln -sf ../usr/share/zoneinfo/America/Phoenix /etc/localtime
      - systemctl mask getty@tty1.service getty-static.service
      - apt-get install -y net-tools wget locales apt-transport-https
      - locale-gen en_US.UTF-8
      - echo LANG=en_US.UTF-8 > /etc/default/locale
    roles:
      - agent
  ubuntu2004-64-1:
    type: aio
    hypervisor: docker
    docker_cmd:
      - "/sbin/init"
    image: ubuntu:20.04
    platform: ubuntu-20.04-amd64
    packaging_platform: ubuntu-20.04-amd64
    docker_image_commands:
      - ln -sf ../usr/share/zoneinfo/America/Phoenix /etc/localtime
      - systemctl mask getty@tty1.service getty-static.service
      - apt-get install -y net-tools wget locales apt-transport-https
      - locale-gen en_US.UTF-8
      - echo LANG=en_US.UTF-8 > /etc/default/locale
    roles:
      - agent
  fedora29-64-1:
    type: aio
    hypervisor: docker
    docker_cmd:
      - "/sbin/init"
    image: fedora:29
    platform: fedora-29-x86_64
    packaging_platform: fedora-29-x86_64
    docker_image_commands:
      - ln -sf ../usr/share/zoneinfo/America/Phoenix /etc/localtime
      - dnf install -y crontabs initscripts iproute openssl tar wget which
    roles:
      - agent
CONFIG:
  nfs_server: none
  consoleport: 443
  docker_preserve_image: true
