---
HOSTS:
  centos7-64-1:
    type: aio
    hypervisor: docker
    docker_cmd:
      - "/sbin/init"
    image: centos:7
    platform: el-7-x86_64
    packaging_platform: el-7-x86_64
    docker_image_commands:
      - ln -sf ../usr/share/zoneinfo/America/Phoenix /etc/localtime
      - systemctl mask getty@tty1.service
      - yum install -y crontabs initscripts iproute openssl sysvinit-tools tar wget which ss
    roles:
      - agent
      - default
  centos6-64-1:
    type: aio
    hypervisor: docker
    docker_cmd:
      - "/sbin/init"
    image: centos:6
    platform: el-6-x86_64
    packaging_platform: el-6-x86_64
    docker_image_commands:
      - ln -sf ../usr/share/zoneinfo/America/Phoenix /etc/localtime
      - rm -rf /var/run/network/*
      - yum install -y crontabs initscripts iproute openssl sysvinit-tools tar wget which
      - rm /etc/init/tty.conf
    roles:
      - agent
  debian8-64-1:
    type: aio
    hypervisor: docker
    docker_cmd:
      - "/sbin/init"
    image: debian:8
    platform: debian-8-amd64
    packaging_platform: debian-8-amd64
    docker_image_commands:
      - ln -sf ../usr/share/zoneinfo/America/Phoenix /etc/localtime
      - rm -f /usr/sbin/policy-rc.d
      - systemctl mask getty@tty1.service getty-static.service
      - apt-get update && apt-get install -y cron locales-all net-tools wget
    roles:
      - agent
  debian9-64-1:
    type: aio
    hypervisor: docker
    docker_cmd:
      - "/sbin/init"
    image: debian:9
    platform: debian-9-amd64
    packaging_platform: debian-9-amd64
    docker_image_commands:
      - ln -sf ../usr/share/zoneinfo/America/Phoenix /etc/localtime
      - rm -f /usr/sbin/policy-rc.d
      - systemctl mask getty@tty1.service getty-static.service
      - apt-get update && apt-get install -y cron locales-all net-tools wget systemd-sysv
    roles:
      - agent
  ubuntu1604-64-1:
    type: aio
    hypervisor: docker
    docker_cmd:
      - "/sbin/init"
    image: ubuntu:16.04
    platform: ubuntu-16.04-amd64
    packaging_platform: ubuntu-16.04-amd64
    docker_image_commands:
      - ln -sf ../usr/share/zoneinfo/America/Phoenix /etc/localtime
      - systemctl mask getty@tty1.service getty-static.service
      - apt-get install -y net-tools wget locales apt-transport-https
      - locale-gen en_US.UTF-8
      - echo LANG=en_US.UTF-8 > /etc/default/locale
    roles:
      - agent
  ubuntu1804-64-1:
    type: aio
    hypervisor: docker
    docker_cmd:
      - "/sbin/init"
    image: ubuntu:18.04
    platform: ubuntu-18.04-amd64
    packaging_platform: ubuntu-18.04-amd64
    docker_image_commands:
      - ln -sf ../usr/share/zoneinfo/America/Phoenix /etc/localtime
      - systemctl mask getty@tty1.service getty-static.service
      - apt-get install -y net-tools wget locales apt-transport-https
      - locale-gen en_US.UTF-8
      - echo LANG=en_US.UTF-8 > /etc/default/locale
    roles:
      - agent
  fedora26-64-1:
    type: aio
    hypervisor: docker
    docker_cmd:
      - "/sbin/init"
    image: fedora:26
    platform: fedora-26-x86_64
    packaging_platform: fedora-26-x86_64
    docker_image_commands:
      - ln -sf ../usr/share/zoneinfo/America/Phoenix /etc/localtime
      - dnf install -y crontabs initscripts iproute openssl tar wget which
    roles:
      - agent
CONFIG:
  nfs_server: none
  consoleport: 443
#  docker_preserve_image: true
